### ISSUE TITLE
Building on Linux

### ISSUE THREAD

**Issue by MarcinWieczorek** [avantol/WSJTX-Controller#1]
Hi,

Have you tried compiling your project on Linux?
Mono and dotnet kind of should still work here on Linux.
We could work on it together if you want to.
It seems to be a nice little program.
Thanks

**Comment by avantol** [comment]
Thanks for writing... I haven't tried porting to Linux, but is sounds interesting!

Let me know how it goes....

73
Andy
WM8Q

**Comment by bertonumber1** [comment]
Dear developer,
Not so much an issue or even as Github context. 
I look for some wisdom from yourself with regard to running your modified version of WSJTX, WSJTX controller and Gridtracker (or any other auto logger) 
As youll know before adding controller the 2237 port was free for Gridtracker or logging program, now we have difficult choice to make to either run WSJTX autonomously or go without logging program.
Is there a way to use something like Com0com?

There must be a way round this or perhaps as a suggestion you could add another drop down menu to select and take care of loggers such as Gridtracker? Not that it sounds as simple as that.

Thank you for your continued development attention to FT8/FT4 softwares.

**Comment by avantol** [comment]
Thanks for writing.... I think the answer is to use multicast UDP, instead
of unicast.

73
Andy
WM8Q

**Comment by n7ekb** [comment]
This tool sounds really good. Unfortunately I run WSJT-X on Linux, so can't try it out.  I'll be watching for a version that matches the portability of the WSJT-X program (Linux/Windows/MAC support).
